[package]
name = "rimforge"
version = "0.1.0"
description = "Profile and mod list manager for RimWorld, built with Tauri"
authors = ["Harry Leach <harry@pluscosmic.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rimforge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
roxmltree = "0.20"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
trash = "5"
dirs = "6"
fs_extra = "1"
regex = "1"

[target.'cfg(windows)'.dependencies]
mslnk = "0.1"
winreg = "0.52"

