// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service bound to the frontend. Every method here is a command
 * in docs/ARCHITECTURE.md; `wails3 generate bindings` turns them into the
 * typed TypeScript in frontend/bindings. Errors reach the frontend as
 * rejected promises carrying the message.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

export function CloneProfile(id: string, newName: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(3462097735, id, newName);
}

export function CreateProfile(name: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(2723389902, name);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2457157279, id);
}

export function DetectPaths(): $CancellablePromise<models$0.DetectedPaths> {
    return $Call.ByID(2789414126);
}

export function GetActiveMods(profileID: string): $CancellablePromise<models$0.ActiveModList> {
    return $Call.ByID(3828357764, profileID);
}

export function GetRulesDbStatus(): $CancellablePromise<models$0.RulesDbStatus> {
    return $Call.ByID(158549430);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2554697378);
}

export function ImportDefault(name: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(979393409, name);
}

export function LaunchProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4232280419, id);
}

export function ListInstalledMods(): $CancellablePromise<models$0.ModInfo[] | null> {
    return $Call.ByID(3640591112);
}

export function ListProfiles(): $CancellablePromise<models$0.Profile[] | null> {
    return $Call.ByID(1957526603);
}

export function RefreshRulesDb(): $CancellablePromise<models$0.RulesDbStatus> {
    return $Call.ByID(1108957189);
}

export function RenameProfile(id: string, newName: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(1067637764, id, newName);
}

/**
 * RevealPath shows a path in the system file manager.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(77851903, path);
}

export function SetActiveMods(profileID: string, activeIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2377189600, profileID, activeIDs);
}

export function SortMods(activeIDs: string[] | null): $CancellablePromise<models$0.SortResult> {
    return $Call.ByID(973585052, activeIDs);
}

export function UpdateSettings(s: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2894041249, s);
}
