// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes the running app.
 */
export interface AppInfo {
    "version": string;
    "dataRoot": string;
}
