// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the game-neutral service bound to the frontend: things about the
 * app itself. Each game module binds its own service (internal/rimworld).
 * Every method here is a command in docs/ARCHITECTURE.md; `wails3 generate
 * bindings` turns them into the typed TypeScript in frontend/bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * GetAppInfo reports the running version and where the app keeps its data.
 */
export function GetAppInfo(): $CancellablePromise<models$0.AppInfo> {
    return $Call.ByID(713661858);
}

/**
 * RevealPath shows a path in the system file manager.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(77851903, path);
}
