// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the game-neutral service bound to the frontend: things about the
 * app itself. Each game module binds its own service (internal/rimworld).
 * Every method here is a command in docs/ARCHITECTURE.md; `wails3 generate
 * bindings` turns them into the typed TypeScript in frontend/bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * CheckForUpdates looks for a newer release and reports whether one exists;
 * when it does, the update window opens and installs it. A failed check (no
 * network, bad manifest) is returned so the UI can say so. Always false when
 * SelfUpdates is false.
 */
export function CheckForUpdates(): $CancellablePromise<boolean> {
    return $Call.ByID(2675659504);
}

/**
 * GetAppInfo reports the running version, where the app keeps its data,
 * whether it can update itself, and which game modules already have data.
 */
export function GetAppInfo(): $CancellablePromise<models$0.AppInfo> {
    return $Call.ByID(713661858);
}

/**
 * GetSettings reads the app's own settings: which game modules are on.
 */
export function GetSettings(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(2554697378);
}

/**
 * RevealPath shows a path in the system file manager.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(77851903, path);
}

/**
 * UpdateSettings persists the app's own settings and echoes back what was
 * stored (unknown game ids dropped, the rest in rail order).
 */
export function UpdateSettings(s: models$0.AppSettings): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(2894041249, s);
}
