// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Minecraft service bound to the frontend. Every method here is
 * a command in docs/ARCHITECTURE.md.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * CheckPack loads the pack and reports what a sync would do, without doing it.
 */
export function CheckPack(id: string): $CancellablePromise<models$0.PackCheck> {
    return $Call.ByID(882074563, id);
}

/**
 * Detect reports the effective manifest URL and launcher location.
 */
export function Detect(): $CancellablePromise<models$0.Detected> {
    return $Call.ByID(1425364701);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(3605983299);
}

/**
 * ListPacks fetches the manifest and pairs each entry with its local state.
 */
export function ListPacks(): $CancellablePromise<models$0.Pack[] | null> {
    return $Call.ByID(2281387124);
}

/**
 * OpenLauncher starts the official Minecraft launcher.
 */
export function OpenLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2445975174);
}

/**
 * SyncPack brings the pack's install directory up to date, makes sure the
 * launcher has the pack's loader, and writes (or refreshes) its launcher
 * profile. Progress goes out on SyncEvent in three phases.
 */
export function SyncPack(id: string): $CancellablePromise<models$0.SyncReport> {
    return $Call.ByID(1529887180, id);
}

export function UpdateSettings(v: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(4087698526, v);
}
