// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Minecraft service bound to the frontend. Every method here is
 * a command in docs/ARCHITECTURE.md.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * CheckPack loads the pack and reports what a sync would do, without doing it.
 */
export function CheckPack(id: string): $CancellablePromise<models$0.PackCheck> {
    return $Call.ByID(882074563, id);
}

/**
 * Detect reports the effective manifest URL, launcher location and memory.
 */
export function Detect(): $CancellablePromise<models$0.Detected> {
    return $Call.ByID(1425364701);
}

/**
 * GetLaunchSettings returns what the pack launches with on this machine.
 */
export function GetLaunchSettings(id: string): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(4055746796, id);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(3605983299);
}

/**
 * LauncherRunning reports whether the official launcher is already open.
 * Opening it again then does nothing, and a profile written since it started
 * is only picked up after it is closed and reopened.
 */
export function LauncherRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(991555629);
}

/**
 * ListPacks fetches the manifest and pairs each entry with its local state.
 */
export function ListPacks(): $CancellablePromise<models$0.Pack[] | null> {
    return $Call.ByID(2281387124);
}

/**
 * OpenLauncher starts the official Minecraft launcher.
 */
export function OpenLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2445975174);
}

/**
 * ResetLaunchSettings forgets the user's launch settings for a pack, going
 * back to the recommendation fitted to this machine, and rewrites the profile.
 */
export function ResetLaunchSettings(id: string): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(2836638715, id);
}

/**
 * SetLaunchSettings saves the user's launch settings for a pack and, when the
 * pack already has a launcher profile, rewrites that profile's javaArgs so the
 * change applies on the next launch without a sync. Returns the settings as
 * stored (clamped to this machine).
 */
export function SetLaunchSettings(id: string, ls: models$0.LaunchSettings): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(3774357824, id, ls);
}

/**
 * SyncPack brings the pack's install directory up to date, makes sure the
 * launcher has the pack's loader, and writes (or refreshes) its launcher
 * profile. Progress goes out on SyncEvent in three phases.
 */
export function SyncPack(id: string): $CancellablePromise<models$0.SyncReport> {
    return $Call.ByID(1529887180, id);
}

export function UpdateSettings(v: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(4087698526, v);
}
