// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Minecraft service bound to the frontend. Every method here is
 * a command in docs/ARCHITECTURE.md.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * AddModrinthPack adds a Modrinth modpack from a pasted modrinth.com link,
 * held at the given version number (or, when blank, the version the link
 * names, else the newest release). The project is looked up, the version
 * checked to exist, and both remembered. Adding a project already present
 * moves it to the chosen version.
 */
export function AddModrinthPack(input: string, version: string): $CancellablePromise<models$0.Pack> {
    return $Call.ByID(3994608401, input, version);
}

/**
 * AddPackCode resolves a code against the registry, remembers it, and returns
 * the pack. Entering a code already present just refreshes it.
 */
export function AddPackCode(input: string): $CancellablePromise<models$0.Pack> {
    return $Call.ByID(1503478745, input);
}

/**
 * CheckPack loads the pack and reports what a sync would do, without doing it.
 */
export function CheckPack(id: string): $CancellablePromise<models$0.PackCheck> {
    return $Call.ByID(882074563, id);
}

/**
 * Detect reports the configured sources, launcher location and memory.
 */
export function Detect(): $CancellablePromise<models$0.Detected> {
    return $Call.ByID(1425364701);
}

/**
 * GetLaunchSettings returns what the pack launches with on this machine.
 */
export function GetLaunchSettings(id: string): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(4055746796, id);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(3605983299);
}

/**
 * LauncherRunning reports whether the official launcher is already open.
 * Opening it again then does nothing, and a profile written since it started
 * is only picked up after it is closed and reopened.
 */
export function LauncherRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(991555629);
}

/**
 * ListModrinthVersions lists the versions of an added Modrinth pack, newest
 * first, for the version picker.
 */
export function ListModrinthVersions(id: string): $CancellablePromise<models$0.ModrinthVersion[] | null> {
    return $Call.ByID(2878569274, id);
}

/**
 * ListPacks lists every pack from the user's codes and pack list, each paired
 * with its local state.
 */
export function ListPacks(): $CancellablePromise<models$0.Pack[] | null> {
    return $Call.ByID(2281387124);
}

/**
 * LookupModrinth reads a pasted modrinth.com link far enough to show the
 * pack and its versions, so the user can choose one before adding. Nothing
 * is saved.
 */
export function LookupModrinth(input: string): $CancellablePromise<models$0.ModrinthLookup> {
    return $Call.ByID(2926086829, input);
}

/**
 * OpenLauncher starts the official Minecraft launcher.
 */
export function OpenLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2445975174);
}

/**
 * RemoveModrinthPack forgets a Modrinth pack by its pack id. Installed files
 * and the launcher profile are left alone.
 */
export function RemoveModrinthPack(id: string): $CancellablePromise<void> {
    return $Call.ByID(1959715574, id);
}

/**
 * RemovePackCode forgets a code. Installed files and the launcher profile are
 * left alone; the pack simply stops being listed.
 */
export function RemovePackCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(2257320678, code);
}

/**
 * ResetLaunchSettings forgets the user's launch settings for a pack, going
 * back to the recommendation fitted to this machine, and rewrites the profile.
 */
export function ResetLaunchSettings(id: string): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(2836638715, id);
}

/**
 * SetLaunchSettings saves the user's launch settings for a pack and, when the
 * pack already has a launcher profile, rewrites that profile's javaArgs so the
 * change applies on the next launch without a sync. Returns the settings as
 * stored (clamped to this machine).
 */
export function SetLaunchSettings(id: string, ls: models$0.LaunchSettings): $CancellablePromise<models$0.LaunchSettings> {
    return $Call.ByID(3774357824, id, ls);
}

/**
 * SetModrinthVersion holds an added Modrinth pack at another version (by
 * number or id). Nothing is installed until the next sync; CheckPack then
 * reports the move. Returns the pack.
 */
export function SetModrinthVersion(id: string, version: string): $CancellablePromise<models$0.Pack> {
    return $Call.ByID(3678651665, id, version);
}

/**
 * SyncPack brings the pack's install directory up to date, makes sure the
 * launcher has the pack's loader, and writes (or refreshes) its launcher
 * profile. Progress goes out on SyncEvent in three phases.
 */
export function SyncPack(id: string): $CancellablePromise<models$0.SyncReport> {
    return $Call.ByID(1529887180, id);
}

export function UpdateSettings(v: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(4087698526, v);
}
