// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Detected is what the module found on this machine.
 */
export interface Detected {
    /**
     * ManifestURL is the effective manifest URL, or nil when none is configured.
     */
    "manifestUrl": string | null;

    /**
     * MinecraftDir is the effective `.minecraft` directory, or nil if unknown.
     */
    "minecraftDir": string | null;

    /**
     * LauncherInstalled: the launcher has run at least once in MinecraftDir.
     */
    "launcherInstalled": boolean;

    /**
     * PacksDir is where packs are installed.
     */
    "packsDir": string;
}

/**
 * Manual is a file the user has to download themselves.
 */
export interface Manual {
    "path": string;
    "name": string;
    "url": string;
    "why": string;
}

/**
 * Pack is a manifest entry plus what is installed locally. Everything from
 * the manifest is present even when nothing is installed.
 */
export interface Pack {
    "id": string;
    "name": string;
    "description": string;
    "icon": string | null;
    "packUrl": string;
    "server": string | null;
    "minMemoryMb": number;
    "maxMemoryMb": number;
    "javaArgs": string[] | null;
    "installDir": string;
    "installed": boolean;
    "installedVersion": string | null;
    "syncedAtMs": number | null;

    /**
     * ProfileWritten: the launcher has our profile for this pack.
     */
    "profileWritten": boolean;
}

/**
 * PackCheck is the result of looking at the pack's current upstream state
 * without changing anything.
 */
export interface PackCheck {
    "id": string;
    "latestVersion": string;
    "minecraft": string;
    "loader": string;
    "loaderVersion": string;

    /**
     * VersionID is the launcher installation id the profile needs.
     */
    "versionId": string;

    /**
     * LoaderInstalled: the launcher already has that installation.
     */
    "loaderInstalled": boolean;
    "toDownload": number;
    "toDelete": number;
    "upToDate": boolean;
}

/**
 * Settings is the module's settings.json.
 */
export interface Settings {
    /**
     * ManifestURLOverride replaces the built-in manifest URL (which is baked in
     * at build time and may be empty).
     */
    "manifestUrlOverride": string | null;

    /**
     * MinecraftDirOverride replaces the detected `.minecraft` directory.
     */
    "minecraftDirOverride": string | null;
}

/**
 * SyncReport is what SyncPack did.
 */
export interface SyncReport {
    "id": string;
    "version": string;
    "downloaded": string[] | null;
    "deleted": string[] | null;
    "manual": Manual[] | null;
    "profileWritten": boolean;

    /**
     * LoaderInstalled: the launcher has the loader installation the profile
     * points at (installed during this sync if it was missing).
     */
    "loaderInstalled": boolean;

    /**
     * VersionID is that installation's id.
     */
    "versionId": string;
}
