// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Detected is what the module found on this machine.
 */
export interface Detected {
    /**
     * ManifestURL is the configured manifest URL, or nil when none is.
     */
    "manifestUrl": string | null;

    /**
     * RegistryURL is the pack registry in use.
     */
    "registryUrl": string;

    /**
     * MinecraftDir is the effective `.minecraft` directory, or nil if unknown.
     */
    "minecraftDir": string | null;

    /**
     * LauncherInstalled: the launcher has run at least once in MinecraftDir.
     */
    "launcherInstalled": boolean;

    /**
     * PacksDir is where packs are installed.
     */
    "packsDir": string;

    /**
     * TotalMemoryMb is this machine's physical memory; 0 if unknown.
     */
    "totalMemoryMb": number;

    /**
     * MaxHeapMb is the largest heap the memory slider offers (about three
     * quarters of TotalMemoryMb); 0 if unknown.
     */
    "maxHeapMb": number;
}

/**
 * LaunchSettings is how a pack is launched on this machine. A pack only
 * recommends; these are what the launcher profile actually gets.
 */
export interface LaunchSettings {
    /**
     * MaxMemoryMb is the Java heap (-Xmx). Clamped to Detected.maxHeapMb.
     */
    "maxMemoryMb": number;

    /**
     * MinMemoryMb is -Xms when set; nil lets the JVM start small and grow.
     */
    "minMemoryMb": number | null;

    /**
     * Args are the extra JVM options.
     */
    "args": string[] | null;

    /**
     * FollowRecommendedArgs: Args track the pack's recommendation as it
     * changes. Editing them pins them (false).
     */
    "followRecommendedArgs": boolean;
}

/**
 * Manual is a file the user has to download themselves.
 */
export interface Manual {
    "path": string;
    "name": string;
    "url": string;
    "why": string;
}

/**
 * ModrinthLookup is what a pasted Modrinth link points at, before it is
 * added: enough to show the pack and pick a version.
 */
export interface ModrinthLookup {
    /**
     * Project is the slug; Input is the link as pasted, to hand back to
     * AddModrinthPack.
     */
    "project": string;
    "input": string;
    "name": string;
    "description": string;
    "icon": string | null;
    "pageUrl": string;

    /**
     * Versions, newest first. Suggested is the one preselected: the link's
     * version when it named one, else the newest release.
     */
    "versions": ModrinthVersion[] | null;
    "suggested": string;

    /**
     * AlreadyAdded: this project is in the list already (at HeldVersion).
     */
    "alreadyAdded": boolean;
    "heldVersion": string | null;
}

/**
 * ModrinthPack is one Modrinth modpack the user added.
 */
export interface ModrinthPack {
    /**
     * ProjectID is Modrinth's stable id for the project; lookups use it.
     */
    "projectId": string;

    /**
     * Slug is the project's slug when it was added; it names the pack
     * (`modrinth-<slug>`) and so the install directory, and stays put even
     * if the project is renamed on Modrinth.
     */
    "slug": string;

    /**
     * Version is the version number the pack is held at. A sync installs
     * exactly this; it only changes when the user picks another (or takes
     * an update), never because Modrinth published one.
     */
    "version": string;
    "addedAtMs": number;

    /**
     * Pack is the project as last seen, in the manifest entry shape (like
     * PackCode.Pack), so the pack stays listed when Modrinth is unreachable.
     */
    "pack": string | null;
}

/**
 * ModrinthVersion is one published version of a Modrinth modpack, for the
 * version picker.
 */
export interface ModrinthVersion {
    "id": string;
    "number": string;

    /**
     * Type is "release", "beta" or "alpha".
     */
    "type": string;
    "publishedAtMs": number;
    "gameVersions": string[] | null;
    "loaders": string[] | null;
}

/**
 * Pack is a manifest entry plus what is installed locally. Everything from
 * the manifest is present even when nothing is installed.
 */
export interface Pack {
    "id": string;
    "name": string;

    /**
     * Source is "code" (entered pack code), "modrinth" (a Modrinth modpack
     * added by link) or "manifest" (from the pack list).
     */
    "source": string;

    /**
     * Code is the pack code this came from, when Source is "code".
     */
    "code": string | null;

    /**
     * Project is the Modrinth project slug, when Source is "modrinth".
     */
    "project": string | null;

    /**
     * HeldVersion is the Modrinth version a sync installs, when Source is
     * "modrinth". Updating is an explicit choice (SetModrinthVersion).
     */
    "heldVersion": string | null;
    "description": string;
    "icon": string | null;
    "packUrl": string;
    "server": string | null;

    /**
     * What the pack's author recommends; advisory.
     */
    "recommendedMinMemoryMb": number;
    "recommendedMaxMemoryMb": number;
    "recommendedArgs": string[] | null;

    /**
     * Launch is what this machine will actually use: the saved settings, or
     * the recommendation fitted to this machine when nothing is saved yet.
     */
    "launch": LaunchSettings;

    /**
     * LaunchCustomised: the user has saved launch settings for this pack.
     */
    "launchCustomised": boolean;
    "installDir": string;
    "installed": boolean;
    "installedVersion": string | null;
    "syncedAtMs": number | null;

    /**
     * ProfileWritten: the launcher has our profile for this pack.
     */
    "profileWritten": boolean;
}

/**
 * PackCheck is the result of looking at the pack's current upstream state
 * without changing anything.
 */
export interface PackCheck {
    "id": string;

    /**
     * LatestVersion is the newest the source offers: pack.toml's version for
     * a packwiz pack, the newest release for a Modrinth pack.
     */
    "latestVersion": string;

    /**
     * TargetVersion is what a sync installs now. For a packwiz pack it is
     * LatestVersion; for a Modrinth pack it is the held version.
     */
    "targetVersion": string;

    /**
     * UpdateAvailable: a newer version exists than the one a sync would
     * install (Modrinth packs only; the user chooses whether to take it).
     */
    "updateAvailable": boolean;
    "minecraft": string;
    "loader": string;
    "loaderVersion": string;

    /**
     * VersionID is the launcher installation id the profile needs.
     */
    "versionId": string;

    /**
     * LoaderInstalled: the launcher already has that installation.
     */
    "loaderInstalled": boolean;
    "toDownload": number;
    "toDelete": number;

    /**
     * UpToDate: the install matches TargetVersion and no file needs work.
     */
    "upToDate": boolean;
}

/**
 * PackCode is one entered code and the registration it resolved to.
 */
export interface PackCode {
    "code": string;
    "addedAtMs": number;

    /**
     * Pack is the registration's pack entry as last seen, as JSON of the
     * manifest entry shape. Kept opaque here so models stays free of the
     * manifest package; the service decodes it.
     */
    "pack": string | null;
}

/**
 * Settings is the module's settings.json.
 */
export interface Settings {
    /**
     * Codes are the pack codes the user has entered, with what each resolved
     * to last time, so the pack list works when the registry is unreachable.
     */
    "codes": PackCode[] | null;

    /**
     * Modrinth is every Modrinth modpack the user added by link, with what
     * each resolved to last time.
     */
    "modrinth": ModrinthPack[] | null;

    /**
     * ManifestURL is an optional pack list (a manifest) the user was given.
     * Muster ships with none: the app knows nothing about any particular pack.
     */
    "manifestUrl": string | null;

    /**
     * RegistryURLOverride replaces the public pack registry (self-hosters).
     */
    "registryUrlOverride": string | null;

    /**
     * MinecraftDirOverride replaces the detected `.minecraft` directory.
     */
    "minecraftDirOverride": string | null;

    /**
     * Packs holds each pack's launch settings, by pack id, once the user has
     * touched them. Absent ⇒ derived from the pack's recommendation and this
     * machine's memory (see LaunchSettings).
     */
    "packs": { [_ in string]?: LaunchSettings } | null;
}

/**
 * SyncReport is what SyncPack did.
 */
export interface SyncReport {
    "id": string;
    "version": string;
    "downloaded": string[] | null;
    "deleted": string[] | null;
    "manual": Manual[] | null;
    "profileWritten": boolean;

    /**
     * LoaderInstalled: the launcher has the loader installation the profile
     * points at (installed during this sync if it was missing).
     */
    "loaderInstalled": boolean;

    /**
     * VersionID is that installation's id.
     */
    "versionId": string;

    /**
     * LauncherOpen: the launcher was running when the profile was written, so
     * it has to be closed and reopened before the pack shows up in it.
     */
    "launcherOpen": boolean;
}
