// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActiveModList {
    "activeIds": string[] | null;
    "knownExpansions": string[] | null;
    "version": string | null;
}

export interface DetectedPaths {
    "steamRoot": string | null;
    "gameInstall": string | null;
    "defaultSavedata": string | null;
    "workshopDirs": string[] | null;
    "gameVersion": string | null;
    "profilesDir": string;
}

export interface ModInfo {
    "packageId": string;
    "name": string;
    "authors": string;
    "path": string;
    "source": ModSource;
    "steamWorkshopId": string | null;
    "supportedVersions": string[] | null;
    "dependencies": string[] | null;
    "loadAfter": string[] | null;
    "loadBefore": string[] | null;
    "forceLoadAfter": string[] | null;
    "forceLoadBefore": string[] | null;
    "incompatibleWith": string[] | null;
}

/**
 * ModSource is where an installed mod was found.
 */
export enum ModSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceOfficial = "official",
    SourceLocal = "local",
    SourceWorkshop = "workshop",
};

export interface Profile {
    "id": string;
    "name": string;
    "path": string;
    "createdAtMs": number;
    "lastPlayedAtMs": number | null;
    "saveCount": number;
    "activeModCount": number;
}

export interface RulesDbStatus {
    "cached": boolean;
    "fetchedAtMs": number | null;
    "ruleCount": number;
}

export interface Settings {
    "steamRootOverride": string | null;
    "gameInstallOverride": string | null;
    "defaultSavedataOverride": string | null;
}

export interface SortResult {
    "sorted": string[] | null;
    "warnings": SortWarning[] | null;
}

export interface SortWarning {
    "kind": string;
    "packageId": string | null;
    "message": string;
}
