// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the RimWorld service bound to the frontend. Every method here is
 * a command in docs/ARCHITECTURE.md; `wails3 generate bindings` turns them
 * into the typed TypeScript in frontend/bindings. Errors reach the frontend as
 * rejected promises carrying the message.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

export function CloneProfile(id: string, newName: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(684188761, id, newName);
}

export function CreateProfile(name: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(2910322408, name);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1711046777, id);
}

export function DetectPaths(): $CancellablePromise<models$0.DetectedPaths> {
    return $Call.ByID(1775277828);
}

export function GetActiveMods(profileID: string): $CancellablePromise<models$0.ActiveModList> {
    return $Call.ByID(3286775870, profileID);
}

export function GetRulesDbStatus(): $CancellablePromise<models$0.RulesDbStatus> {
    return $Call.ByID(1814935480);
}

export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(3998201364);
}

export function ImportDefault(name: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(3631251779, name);
}

export function LaunchProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3894680501, id);
}

export function ListInstalledMods(): $CancellablePromise<models$0.ModInfo[] | null> {
    return $Call.ByID(1202215882);
}

export function ListProfiles(): $CancellablePromise<models$0.Profile[] | null> {
    return $Call.ByID(791997665);
}

export function RefreshRulesDb(): $CancellablePromise<models$0.RulesDbStatus> {
    return $Call.ByID(2714623811);
}

export function RenameProfile(id: string, newName: string): $CancellablePromise<models$0.Profile> {
    return $Call.ByID(3910049646, id, newName);
}

export function SetActiveMods(profileID: string, activeIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(725578010, profileID, activeIDs);
}

export function SortMods(activeIDs: string[] | null): $CancellablePromise<models$0.SortResult> {
    return $Call.ByID(3394035746, activeIDs);
}

export function UpdateSettings(v: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(1562183883, v);
}
